safety_distance: 1240
unload_speed: 93
fractional_load_speed: 62
heavy_load_speed: 49.6
able_process_distance: 48.98
real_action_time: 30

vehicles:
  Cranes:
    crane1_1:
      other_dim_pos: 8402
      LowerMovingPos: 2970
      UpperMovingPos: 16183
      InitLowerLimit: 2976
      InitUpperLimit: 7998
      connections:
        - trolley2_2
        - trolley_3
        - trolley_4
        - trolley_5
        - trolley_6
        - trolley_7
        - trolley_8
        - trolley_9
        - trolley_10
    crane1_2:
      other_dim_pos: 8402
      LowerMovingPos: 2970
      UpperMovingPos: 16183
      InitLowerLimit: 9330
      InitUpperLimit: 16554
      connections:
        - trolley2_2
        - trolley_3
        - trolley_4
        - trolley_5
        - trolley_6
        - trolley_7
        - trolley_8
        - trolley_9
        - trolley_10
    crane2:
      other_dim_pos: 6663
      LowerMovingPos: 4569
      UpperMovingPos: 9883
      InitLowerLimit: 4569
      InitUpperLimit: 9883
      connections:
        - trolley_3
        - trolley_4
        - trolley_5
        - trolley_6
    crane3:
      other_dim_pos: 4932
      LowerMovingPos: 700
      UpperMovingPos: 9883
      InitLowerLimit: 700
      InitUpperLimit: 9883
      connections:
        - trolley1_1
        - trolley2_2
        - trolley2_1
        - trolley_3
        - trolley_4
        - trolley_5
        - trolley_6
    crane5:
      other_dim_pos: 845
      LowerMovingPos: 700
      UpperMovingPos: 9883
      InitLowerLimit: 700
      InitUpperLimit: 9883
      connections:
        - trolley1_2
        - trolley2_2
        - trolley_3
        - trolley_4
        - trolley_5
        - trolley_6

  Trolleys:
    trolley1_1:
      other_dim_pos: 700
      LowerMovingPos: 845
      UpperMovingPos: 3266
      InitLowerLimit: 806
      InitUpperLimit: 2542
      connections:
        - crane5
    trolley1_2:
      other_dim_pos: 700
      LowerMovingPos: 3266
      UpperMovingPos: 4932
      InitLowerLimit: 3782
      InitUpperLimit: 4898
      connections:
        - crane3
    trolley2_1:
      other_dim_pos: 2970
      LowerMovingPos: 845
      UpperMovingPos: 4932
      InitLowerLimit: 806
      InitUpperLimit: 4092
      connections:
        - crane3
        - crane5
    trolley2_2:
      other_dim_pos: 2970
      LowerMovingPos: 3266
      UpperMovingPos: 9140
      InitLowerLimit: 5766
      InitUpperLimit: 8742
      connections:
        - crane1_1
        - crane1_2
        - crane3
    trolley_3:
      other_dim_pos: 4569
      LowerMovingPos: 845
      UpperMovingPos: 10393
      InitLowerLimit: 845
      InitUpperLimit: 10393
      connections:
        - crane1_1
        - crane1_2
        - crane3
        - crane2
        - crane5
    trolley_4:
      other_dim_pos: 6321
      LowerMovingPos: 845
      UpperMovingPos: 10393
      InitLowerLimit: 845
      InitUpperLimit: 10393
      connections:
        - crane1_1
        - crane1_2
        - crane3
        - crane2
        - crane5
    # Trolly5_1涉及到逆物流问题,此轨道能和加料跨交互,能到达182.这里不考虑,因此限制到173
    trolley_5:
      other_dim_pos: 8085
      LowerMovingPos: 845
      UpperMovingPos: 10393
      InitLowerLimit: 845
      InitUpperLimit: 10393
      connections:
        - crane1_1
        - crane1_2
        - crane3
        - crane2
        - crane5
    trolley_6:
      other_dim_pos: 9883
      LowerMovingPos: 845
      UpperMovingPos: 8402
      InitLowerLimit: 845
      InitUpperLimit: 8402
      connections:
        - crane1_1
        - crane1_2
        - crane3
        - crane2
        - crane5
    trolley_7:
      other_dim_pos: 9385
      LowerMovingPos: 8402
      UpperMovingPos: 9370
      InitLowerLimit: 8402
      InitUpperLimit: 9370
      connections:
        - crane1_1
        - crane1_2
    trolley_8:
      other_dim_pos: 10418
      LowerMovingPos: 8402
      UpperMovingPos: 9370
      InitLowerLimit: 8402
      InitUpperLimit: 9370
      connections:
        - crane1_1
        - crane1_2
    trolley_9:
      other_dim_pos: 13703
      LowerMovingPos: 8402
      UpperMovingPos:  9454
      InitLowerLimit: 8402
      InitUpperLimit: 9454
      connections:
        - crane1_1
        - crane1_2
    trolley_10:
      other_dim_pos: 14891
      LowerMovingPos: 8402
      UpperMovingPos:  9454
      InitLowerLimit: 8402
      InitUpperLimit: 9454
      connections:
        - crane1_1
        - crane1_2

Track:
  horizontal:
    bridge1:
      other_dim_pos: 8402
      low: 2970
      high: 17794
      num_crane: 2
    bridge2:
      other_dim_pos: 6663
      low: 4569
      high: 9883
      num_crane: 1
    bridge3:
      other_dim_pos: 4932
      low: 700
      high: 9883
      num_crane: 1
    bridge5:
      other_dim_pos: 845
      low: 700
      high: 9883
      num_crane: 1
  vertical:
    trolley_track_1:
      other_dim_pos: 700
      low: 845
      high: 4932
    trolley_track_2:
      other_dim_pos: 2970
      low: 845
      high: 9140
    trolley_track_3:
      other_dim_pos: 4569
      low: 845
      high: 10393
    trolley_track_4:
      other_dim_pos: 6321
      low: 845
      high: 10393
    trolley_track_5:
      other_dim_pos: 8085
      low: 845
      high: 10393
    trolley_track_6:
      other_dim_pos: 9883
      low: 845
      high: 8402
    trolley_track_7:
      other_dim_pos: 9385
      low: 8402
      high: 9370
    trolley_track_8:
      other_dim_pos: 10418
      low: 8402
      high: 9370
    trolley_track_9:
      other_dim_pos: 13703
      low: 8402
      high: 9454
    trolley_track_10:
      other_dim_pos: 14891
      low: 8402
      high: 9454

poses:
  1LD:
    x: 4569
    y: 10393
    connections:
      - 1LD1
  2LD:
    x: 6321
    y: 10393
    connections:
      - 2LD1
  3LD:
    x: 8085
    y: 10393
    connections:
      - 3LD1
  4LF_left:
    x: 9385
    y: 9370
    connections:
      - 4LF1
  4LF_right:
    x: 10418
    y: 9370
    connections:
      - 4LF2
  2RH_left:
    x: 13703
    y: 9454
    connections:
      - 2RH1
  2RH_right:
    x: 14891
    y: 9454
    connections:
      - 2RH2
  1LF:
    x: 2970
    y: 9140
    connections:
      - 1LF1
  1CC:
    x: 14773
    y: 8402
    connections:
      - 2RH2
      - 2RH1
  2CC:
    x: 16183
    y: 8402
    connections:
      - 2RH2
  4RH:
    x: 700
    y: 3266
    connections:
      - 4RH3
      - 4RH5
  2LF:
    x: 2970
    y: 3357
    connections:
      - 2LF3
      - 2LF5
  1RH:
    x: 9883
    y: 3082
    connections:
      - 1RH3
      - 1RH5
  3CC:
    x: 2116
    y: 845
    connections:
      - 4RH5
      - 2LF5
  1LF1:
    x: 2970
    y: 8402
    connections:
      - 1LF
      - 1LD1
      - 2LF3
  1LD1:
    x: 4569
    y: 8402
    connections:
      - 1LD
      - 1LF1
      - 1LD2
      - 2LD1
  2LD1:
    x: 6321
    y: 8402
    connections:
      - 2LD
      - 1LD1
      - 2LD2
      - 3LD1
  3LD1:
    x: 8085
    y: 8402
    connections:
      - 3LD
      - 2LD1
      - 3LD2
      - 4LF1
  4LF1:
    x: 9385
    y: 8402
    connections:
      - 4LF_left
      - 3LD1
      - 1RH1
  4LF2:
    x: 10418
    y: 8402
    connections:
      - 4LF_right
      - 2RH1
      - 1RH1
  1RH1:
    x: 9883
    y: 8402
    connections:
      - 4LF1
      - 4LF2
      - 1RH2
  2RH1:
    x: 13703
    y: 8402
    connections:
      - 1CC
      - 4LF2
      - 2RH_left
  2RH2:
    x: 14891
    y: 8402
    connections:
      - 1CC
      - 2CC
      - 2RH_right
  1LD2:
    x: 4569
    y: 6663
    connections:
      - 2LD2
      - 1LD1
      - 1LD3
  2LD2:
    x: 6321
    y: 6663
    connections:
      - 2LD1
      - 1LD2
      - 3LD2
      - 2LD3
  3LD2:
    x: 8085
    y: 6663
    connections:
      - 3LD1
      - 2LD2
      - 1RH2
      - 3LD3
  1RH2:
    x: 9883
    y: 6663
    connections:
      - 3LD2
      - 1RH1
      - 1RH3
  4RH3:
    x: 700
    y: 4932
    connections:
      - 2LF3
      - 4RH
  2LF3:
    x: 2970
    y: 4932
    connections:
      - 4RH3
      - 2LF
      - 1LD3
  1LD3:
    x: 4569
    y: 4932
    connections:
      - 2LF3
      - 1LD2
      - 2LD3
      - 1LD5
  2LD3:
    x: 6321
    y: 4932
    connections:
      - 1LD3
      - 3LD3
      - 2LD2
      - 2LD5
  3LD3:
    x: 8085
    y: 4932
    connections:
      - 2LD3
      - 3LD2
      - 3LD5
      - 1RH3
  1RH3:
    x: 9883
    y: 4932
    connections:
      - 3LD3
      - 1RH2
      - 1RH
  4RH5:
    x: 700
    y: 845
    connections:
      - 4RH
      - 3CC
  2LF5:
    x: 2970
    y: 845
    connections:
      - 2LF
      - 3CC
      - 1LD5
  1LD5:
    x: 4569
    y: 845
    connections:
      - 1LD3
      - 2LF5
      - 2LD5
  2LD5:
    x: 6321
    y: 845
    connections:
      - 1LD5
      - 3LD5
      - 2LD3
  3LD5:
    x: 8085
    y: 845
    connections:
      - 2LD5
      - 3LD3
      - 1RH5
  1RH5:
    x: 9883
    y: 845
    connections:
      - 3LD5
      - 1RH


# connections为一步能到达的周围节点
Station_Layout:
  workstations:
    1LD:
      x: 4569
      y: 10393
      connections:
        - 1LD1
      vehicle:
        - trolley_3
    2LD:
      x: 6321
      y: 10393
      connections:
        - 2LD1
      vehicle:
        - trolley_4
    3LD:
      x: 8085
      y: 10393
      connections:
        - 3LD1
      vehicle:
        - trolley_5
    4LF_left:
      x: 9385
      y: 9370
      connections:
        - 4LF1
      vehicle:
        - trolley_7
    4LF_right:
      x: 10418
      y: 9370
      connections:
        - 4LF2
      vehicle:
        - trolley_8
    2RH_left:
      x: 13703
      y: 9454
      connections:
        - 2RH1
      vehicle:
        - trolley_9
    2RH_right:
      x: 14891
      y: 9454
      connections:
        - 2RH2
      vehicle:
        - trolley_10
    1LF:
      x: 2970
      y: 9140
      connections:
        - 1LF1
      vehicle:
        - trolley2_2
    1CC:
      x: 14773
      y: 8402
      connections:
        - 2RH2
        - 2RH1
      vehicle:
        - crane1_1
        - crane1_2
    2CC:
      x: 16183
      y: 8402
      connections:
        - 2RH2
      vehicle:
        - crane1_1
        - crane1_2
    4RH:
      x: 700
      y: 3266
      connections:
        - 4RH3
        - 4RH5
      vehicle:
        - trolley1_1
        - trolley1_2
    2LF:
      x: 2970
      y: 3357
      connections:
        - 2LF3
        - 2LF5
      vehicle:
        - trolley2_1
        - trolley2_2
    1RH:
      x: 9883
      y: 3082
      connections:
        - 1RH3
        - 1RH5
      vehicle:
        - trolley_6
    3CC:
      x: 2116
      y: 845
      connections:
        - 4RH5
        - 2LF5
      vehicle:
        - crane5
  # 交互位置
  intersections:
    1LF1:
      x: 2970
      y: 8402
      connections:
        - 1LF
        - 1LD1
        - 2LF3
    1LD1:
      x: 4569
      y: 8402
      connections:
        - 1LD
        - 1LF1
        - 1LD2
        - 2LD1
    2LD1:
      x: 6321
      y: 8402
      connections:
        - 2LD
        - 1LD1
        - 2LD2
        - 3LD1
    3LD1:
      x: 8085
      y: 8402
      connections:
        - 3LD
        - 2LD1
        - 3LD2
        - 4LF1
    4LF1:
      x: 9385
      y: 8402
      connections:
        - 4LF_left
        - 3LD1
        - 1RH1
    4LF2:
      x: 10418
      y: 8402
      connections:
        - 4LF_right
        - 2RH1
        - 1RH1
    1RH1:
      x: 9883
      y: 8402
      connections:
        - 4LF1
        - 4LF2
        - 1RH2
    2RH1:
      x: 13703
      y: 8402
      connections:
        - 1CC
        - 4LF2
        - 2RH_left
    2RH2:
      x: 14891
      y: 8402
      connections:
        - 1CC
        - 2CC
        - 2RH_right
    1LD2:
      x: 4569
      y: 6663
      connections:
        - 2LD2
        - 1LD1
        - 1LD3
    2LD2:
      x: 6321
      y: 6663
      connections:
        - 2LD1
        - 1LD2
        - 3LD2
        - 2LD3
    3LD2:
      x: 8085
      y: 6663
      connections:
        - 3LD1
        - 2LD2
        - 1RH2
        - 3LD3
    1RH2:
      x: 9883
      y: 6663
      connections:
        - 3LD2
        - 1RH1
        - 1RH3
    4RH3:
      x: 700
      y: 4932
      connections:
        - 2LF3
        - 4RH
    2LF3:
      x: 2970
      y: 4932
      connections:
        - 1LF1
        - 4RH3
        - 2LF
        - 1LD3
    1LD3:
      x: 4569
      y: 4932
      connections:
        - 2LF3
        - 1LD2
        - 2LD3
        - 1LD5
    2LD3:
      x: 6321
      y: 4932
      connections:
        - 1LD3
        - 3LD3
        - 2LD2
        - 2LD5
    3LD3:
      x: 8085
      y: 4932
      connections:
        - 2LD3
        - 3LD2
        - 3LD5
        - 1RH3
    1RH3:
      x: 9883
      y: 4932
      connections:
        - 3LD3
        - 1RH2
        - 1RH
    4RH5:
      x: 700
      y: 845
      connections:
        - 4RH
        - 3CC
    2LF5:
      x: 2970
      y: 845
      connections:
        - 2LF
        - 3CC
        - 1LD5
    1LD5:
      x: 4569
      y: 845
      connections:
        - 1LD3
        - 2LF5
        - 2LD5
    2LD5:
      x: 6321
      y: 845
      connections:
        - 1LD5
        - 3LD5
        - 2LD3
    3LD5:
      x: 8085
      y: 845
      connections:
        - 2LD5
        - 3LD3
        - 1RH5
    1RH5:
      x: 9883
      y: 845
      connections:
        - 3LD5
        - 1RH